### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Sabrinalily22** [khanhas/ShapeCorners#10]
Sorry if this is a bit of a dumb question, but I can't seem to remove the rounded corners. I've deleted all the relevant files as I can see

**Comment by WillyJL** [comment]
Disable them from system settings, Workspace Behavior > Desktop Effects > Find ShapeCorners and disable it

**Comment by Sabrinalily22** [comment]
That doesn't work if you delete the files. But it still stayed active. I reinstalled and fixed the issue I was having(turned off shadows) just for anyone else is there a way to properly uninstall?

But really like the curved windows and I'm sticking with it :)

**Comment by WillyJL** [comment]
I mean... if it's loaded and you want to remove it from settings you need to do it how I said in the previous comment I made, while if you deleted it you can't from settings... but if the files are deleted, it won't be able to load the effect after a restart right? So if you delete the files, either try restarting kwin (`kwin_x11 --replace &`) or restart your pc? That will remove it from memory and it will not be able to load it again...
